# use alpine linux with standard python-3.9
FROM python:3.9-alpine

# install necessities and c compilers for msSQL drivers compilation
RUN apk update && apk upgrade && apk add g++ gcc

# open up port 5000
EXPOSE 5000

# set working directory
WORKDIR /server

# copy files over
COPY requirements.txt /server/requirements.txt

# set env variables
ENV FLASK_ENV development
ENV DEBUG true

# install python dependencies
RUN pip install -r requirements.txt

# spin up gcloud functions server
CMD ["functions-framework", "--target=dispatcher", "--port=5000", "--debug"]